stages:
    - runSAST

run-sast-job:
    stage: runSAST
    image: maven:3.8.5-openjdk-11-slim
    script: |
      apt-get update
      apt-get -y install curl jq
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=gitlabdevsecopsintegrtion -Dsonar.projectKey=gitLabdevsecopsintegration -Dsonar.login=14ad4797c02810a818f21384add02744d3f9e34d
      sleep 5 
      quality_status=$(curl -s -u 14ad4797c02810a818f21384add02744d3f9e34d: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gitLabdevsecopsintegration | jq -r '.projectStatus.status')
      echo "SonarCloud Analysis Status is $quality_status"; 
      if [[ $quality_status == "ERROR" ]] ; then exit 1;fi
